FROM python:3.7-slim

COPY ./tapo-estream/main.py /app/tapo-estream/
WORKDIR /app/tapo-estream/
RUN apt-get update && apt-get install -y build-essential 
RUN pip install --upgrade pip && pip install PyP100

CMD ["python3", "main.py"]